# Generated by Django 4.0.1 on 2022-04-30 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='by',
            field=models.CharField(default='superuser', max_length=100),
            preserve_default=False,
        ),
    ]
