# Generated by Django 4.0.1 on 2022-01-16 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapter1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='roll',
            field=models.IntegerField(unique=True),
        ),
    ]
